#!/usr/bin/bash
###
### Author: ron.tapia@ligo.org
### Date:   Apr 18, 2020
### Desc: Install CVMFS and configure it for LIGO data via the Gravitational Wave Open Science Center
###       
### Based on:
###
###   https://www.gw-openscience.org/cvmfs/
###   https://cernvm.cern.ch/portal/filesystem/quickstart
###
##
## Install.
##
yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
yum install -y cvmfs cvmfs-config-default

##
## Configure. This configures the automounter.
##
cvmfs_config setup
echo "CVMFS_HTTP_PROXY=DIRECT" > /etc/cvmfs/default.local

cat - > /etc/cvmfs/default.d/60-osg.conf <<EOF
EOF
# /etc/cvmfs/default.d/60-osg.conf
#
# DO NOT EDIT THIS FILE
# It will be replaced on upgrade. To override, edit /etc/cvmfs/default.local
#
CVMFS_SEND_INFO_HEADER=yes
CVMFS_KEYS_DIR=/etc/cvmfs/keys/opensciencegrid.org
CVMFS_USE_GEOAPI=yes
CVMFS_CONFIG_REPOSITORY=config-osg.opensciencegrid.org
CVMFS_CONFIG_REPO_REQUIRED=yes
CVMFS_FALLBACK_PROXY=http://cvmfsbproxy.cern.ch:3126;http://cvmfsbproxy.fnal.gov:3126
EOF

echo "CVMFS_SERVER_URL=http://cvmfs-s1bnl.opensciencegrid.org:8000/cvmfs/@fqrn@;http://cvmfs-s1fnal.opensciencegrid.org:8000/cvmfs/@fqrn@;http://cvmfs-s1goc.opensciencegrid.org:8000/cvmfs/@fqrn@" > /etc/cvmfs/config.d/config-osg.opensciencegrid.org.conf 

##
## Create mount points.
##
mkdir -p /cvmfs/config-osg.opensciencegrid.org
mkdir -p /cvmfs/oasis.opensciencegrid.org
mkdir -p /cvmfs/gwosc.osgstorage.org

##
## Mount file systems if necessary. They should be auto mounted.
## 
#mount -t cvmfs config-osg.opensciencegrid.org /cvmfs/config-osg.opensciencegrid.org
#mount -t cvmfs oasis.opensciencegrid.org /cvmfs/oasis.opensciencegrid.org
#mount -t cvmfs gwosc.osgstorage.org /cvmfs/gwosc.osgstorage.org
